
name: Build website

on:
  push:
   branches: [ develop ]

jobs:
 build:
    runs-on: ubuntu-latest
    env:
      website-dir: ./website

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
        working-directory: ${{env.website-dir}}
      - run: npm build
        working-directory: ${{env.website-dir}}
